CREATE DATABASE IF NOT EXISTS EMPRESA;

USE EMPRESA;

CREATE TABLE IF NOT EXISTS EMPLEADO (
  CEDULA VARCHAR(10)  NOT NULL  ,
  NOMBRE VARCHAR(50)  NULL  ,
  SALARIO_BASICO FLOAT  NULL  ,
  SUBSIDIO FLOAT  NULL  ,
  SALUD FLOAT  NULL  ,
  PENSION FLOAT  NULL  ,
  BONO FLOAT  NULL  ,
  SALARIO_INTEGRAL FLOAT  NULL    ,
PRIMARY KEY(CEDULA));

insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('31273424', 'Kristoforo', 1000000, NULL, NULL, NULL, NULL,null);
insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('6873670', 'Lawrence', 2000000, NULL, NULL, NULL, NULL,null);
insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('47262403', 'Anabal', 3000000, NULL, NULL, NULL, NULL,null);
insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('106584879', 'Felecia', 400000, NULL, NULL, NULL, NULL,null);
insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('142980097', 'Viviana', 500000, NULL, NULL, NULL, NULL,null);
insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('139115006', 'Darrick', 600000, NULL, NULL, NULL, NULL,null);
insert into EMPLEADO (CEDULA, NOMBRE, SALARIO_BASICO, SUBSIDIO, SALUD, PENSION, BONO, SALARIO_INTEGRAL) values ('93996005', 'Oates', 700000, NULL, NULL, NULL, NULL,null);







