CREATE DATABASE IF NOT EXISTS HOSPITAL;

USE HOSPITAL;

CREATE TABLE IF NOT EXISTS PERSONA(
    PESO FLOAT NOT NULL,
    ESTADO VARCHAR(50) NULL,
    PRIMARY KEY(PESO));

insert into PERSONA (PESO, ESTADO) values (28, 'NO ADMITIDO');
insert into PERSONA (PESO, ESTADO) values (85, 'ADMITIDO');
insert into PERSONA (PESO, ESTADO) values (69, 'ADMITIDO');
insert into PERSONA (PESO, ESTADO) values (46, 'NO ADMITIDO');
insert into PERSONA (PESO, ESTADO) values (25, 'NO ADMITIDO');
insert into PERSONA (PESO, ESTADO) values (15, 'NO ADMITIDO');
insert into PERSONA (PESO, ESTADO) values (33, 'NO ADMITIDO');

